.circleci/config.yml
jobs-core/pom.xml
lms-jobs/activity-aggregate-updater/pom.xml
lms-jobs/credential-generator/pom.xml
lms-jobs/enrolment-reconciliation/pom.xml
lms-jobs/pom.xml
lms-jobs/relation-cache-updater/pom.xml
pom.xml

Issue #SB-30075 fix: sonar project key and organization

---

jobs-distribution/pom.xml

fix:jobs-distribution with merge-course details

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Local 5.0.0

---

kubernetes/pipelines/build/auto_build_deploy

 fix:SB-30068 modified script for auto build deploy

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:SB-30068 modified deployment variables

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

fix:SB-30068 added redis_timeout

---

ansible/inventory/env/group_vars/all.yml
ansible/roles/setup-kafka/defaults/main.yml
ansible/roles/setup-kafka/tasks/main.yml
dp-core/src/main/resources/base-config.conf
jobs-core/src/main/resources/base-config.conf
kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:SB-30068  added kafka setup files

---

ansible/lern_kafka_setup.yml
kubernetes/pipelines/deploy/kafka/Jenkinsfile

feat:SB-20063 kafka setup job changes

---

ansible/inventory/env/group_vars/all.yml
ansible/lern_kafka_setup.yml
ansible/roles/setup-lern-kafka/defaults/main.yml
ansible/roles/setup-lern-kafka/tasks/main.yml

feat:SB-20063 kafka setup job changes 

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

config property changes-1

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

flink config changes

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

flink config changes-1

---

notification/notification-job/src/main/scala/org/sunbird/job/notification/function/NotificationFunction.scala

SB-28322 processing failed request for 2nd time

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-124 changed kafka topics for ed

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-124 modified the value

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-124 multiDC enabled value

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-124 multiDC value

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-124 added missing variables

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-124 false set for multi DC

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

fix:LR-124 fix bad character list

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-105 reverted back kafka topic names

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-105 using kafka topic variables

---

ansible/inventory/env/group_vars/all.yml

fix:LR-105 added kafka topic variables to lern pipeline

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

fix:LR-105 matching devops variable name

---

ansible/inventory/env/group_vars/all.yml

LR-269 using same variable from private repo

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/resources/collection-cert-pre-processor.conf
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/task/CollectionCertPreProcessorConfig.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/test/resources/test.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/resources/collection-certificate-generator.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/resources/test.conf

LR-265 modified variable name

---

kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml

LR-262 modified the variable name

---

lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/NotifierFunction.scala

ED-621:templateUrl placeholder replace fix

---

lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala

ED-621:templateUrl placeholder value changed

---

lms-jobs/relation-cache-updater/src/main/scala/org/sunbird/job/relationcache/functions/RelationCacheUpdater.scala
lms-jobs/relation-cache-updater/src/test/scala/org/sunbird/job/spec/RelationCacheUpdaterTaskTestSpec.scala

LR-1  updating the optional nodes list

---

lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala

ED-621: added loggers to check the templateUrl

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/resources/collection-cert-pre-processor.conf
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/task/CollectionCertPreProcessorConfig.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/test/resources/test.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/resources/collection-certificate-generator.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/resources/test.conf

ED-621 place holder variable added to config files

---

ansible/inventory/env/group_vars/all.yml

ED-621 place holder variable added with default value

---

ansible/inventory/env/group_vars/all.yml

ED-621: removed reference variable for placeholder

---

ansible/inventory/env/group_vars/all.yml

ED-621: Update value

---

ansible/inventory/env/group_vars/all.yml

ED-621 modified variable

---

ansible/inventory/env/group_vars/all.yml
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/task/CollectionCertPreProcessorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala

ED-621 added placeholder value

---

lms-jobs/relation-cache-updater/src/main/scala/org/sunbird/job/relationcache/functions/RelationCacheUpdater.scala
lms-jobs/relation-cache-updater/src/test/scala/org/sunbird/job/spec/RelationCacheUpdaterTaskTestSpec.scala

Reverts Sunbird-Lern/data-pipeline#54

Revert "LR-1  updating the optional nodes list"

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2

LR-269 | CSP changes for Checkpointing added

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/resources/collection-cert-pre-processor.conf
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/functions/IssueCertificateHelper.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/task/CollectionCertPreProcessorConfig.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/test/resources/test.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/resources/collection-certificate-generator.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/NotifierFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/resources/test.conf

LR-278 added container to the base path while resolving

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2

* LR-269 | CSP changes for Checkpointing added
* LR-269 | CSP changes for Checkpointing added
Co-authored-by: kumarks1122 <kumar.kandasamy@tarento.com>
Co-authored-by: Reshmi V Nair <54312456+reshmi-nair@users.noreply.github.com>

Release 5.0.1 (#76)

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/resources/collection-cert-pre-processor.conf
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/functions/IssueCertificateHelper.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/task/CollectionCertPreProcessorConfig.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/test/resources/test.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/resources/collection-certificate-generator.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/NotifierFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/resources/test.conf

* LR-269 | CSP changes for Checkpointing added
* LR-269 | CSP changes for Checkpointing added
* LR-278 added container to the base path while resolving
* LR-278 cname related changes
* LR-278 added cname url
* LR-278 added missing variable in test config
Co-authored-by: kumarks1122 <kumar.kandasamy@tarento.com>
Co-authored-by: Reshmi V Nair <54312456+reshmi-nair@users.noreply.github.com>
Co-authored-by: PrasadMoka <prasad@sanketika.in>
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any …

Release 5.0.1 (#79)

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

LR-303 adding configurations to user-cache-job

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

LR-303 modified property value

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

fixing the property-user_read_api_endpoint

---

jobs-distribution/pom.xml

LR-303 added user-cache-updater to job-distribution

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

LR-303 added property task.usercache.updater.parallelism

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

reverting cloud_storage keys

---

lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/functions/IssueCertificateHelper.scala

Issue #LR-323 feat: Course Progress Exhaust to capture number of attempts

---

lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/functions/IssueCertificateHelper.scala

Issue #LR-402 fix: Course attempts not getting passed

---

ansible/roles/setup-lern-kafka/defaults/main.yml
ansible/roles/setup-lern-kafka/tasks/main.yml

Issue LR-102 chore: Removed the bb variable

---

ansible/inventory/env/group_vars/all.yml
lms-jobs/credential-generator/legacy-certificate-migrator/README.md

LR-437 | Config changes added

---

README.md
notification/notification-job/src/main/resources/notification-job.conf
notification/notification-job/src/main/scala/org/sunbird/job/notification/domain/Event.scala
notification/notification-job/src/main/scala/org/sunbird/job/notification/function/NotificationFunction.scala

Issue #LR-451 feat: Local setup documentation update

---

ansible/roles/setup-lern-kafka/defaults/main.yml

LR-539 | Ansible changes added

---

ansible/inventory/env/group_vars/all.yml

Issue #LR-437 merge: from master to release-5.4.0

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #LR-511 fix:Issue fix wrt default values in j2 file on shared instances

---

ansible/roles/setup-lern-kafka/defaults/main.yml

Addedd user-info related topics

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

Lr 511 fix ability for lern to connect to shared instances of cassandra es postgres redis with lern specific keyspace and indexes in datapipeline

---

.circleci/config.yml
ansible/inventory/env/group_vars/all.yml
jobs-core/pom.xml
jobs-distribution/Dockerfile
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/activity-aggregate-updater/src/main/scala/org/sunbird/job/aggregate/functions/ActivityAggregatesFunction.scala
lms-jobs/activity-aggregate-updater/src/main/scala/org/sunbird/job/aggregate/functions/ContentConsumptionDeDupFunction.scala
lms-jobs/credential-generator/certificate-processor/pom.xml
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/CertificateConfig.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/processor/store/StorageService.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/functions/IssueCertificateHelper.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorStreamTask.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/scala/org/sunbird/job/certgen/spec/CertificateGeneratorFunctionTest.scala
lms-jobs/relation-cache-updater/src/main/scala/org/sunbird/job/relationcache/functions/RelationCacheUpdater.scala

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.1.0

---

.circleci/config.yml
ansible/inventory/env/group_vars/all.yml
jobs-core/pom.xml
jobs-distribution/Dockerfile
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/activity-aggregate-updater/src/main/scala/org/sunbird/job/aggregate/functions/ActivityAggregatesFunction.scala
lms-jobs/activity-aggregate-updater/src/main/scala/org/sunbird/job/aggregate/functions/ContentConsumptionDeDupFunction.scala
lms-jobs/credential-generator/certificate-processor/pom.xml
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/CertificateConfig.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/processor/store/StorageService.scala
lms-jobs/credential-generator/collection-cert-pre-processor/src/main/scala/org/sunbird/job/collectioncert/functions/IssueCertificateHelper.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorStreamTask.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/scala/org/sunbird/job/certgen/spec/CertificateGeneratorFunctionTest.scala
lms-jobs/relation-cache-updater/src/main/scala/org/sunbird/job/relationcache/functions/RelationCacheUpdater.scala

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.1.1

---

.circleci/config.yml
ansible/inventory/env/group_vars/all.yml
jobs-core/pom.xml
jobs-distribution/Dockerfile
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/activity-aggregate-updater/src/main/scala/org/sunbird/job/aggregate/functions/ContentConsumptionDeDupFunction.scala
lms-jobs/credential-generator/certificate-processor/pom.xml
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/CertificateConfig.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/processor/store/StorageService.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorStreamTask.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/scala/org/sunbird/job/certgen/spec/CertificateGeneratorFunctionTest.scala
lms-jobs/relation-cache-updater/src/main/scala/org/sunbird/job/relationcache/functions/RelationCacheUpdater.scala

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.2.0

---

ansible/inventory/env/group_vars/all.yml
jobs-core/pom.xml
jobs-distribution/Dockerfile
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/activity-aggregate-updater/src/main/scala/org/sunbird/job/aggregate/functions/ContentConsumptionDeDupFunction.scala
lms-jobs/credential-generator/certificate-processor/pom.xml
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/CertificateConfig.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/processor/store/StorageService.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorStreamTask.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/resources/test.conf
lms-jobs/credential-generator/collection-certificate-generator/src/test/scala/org/sunbird/job/certgen/spec/CertificateGeneratorFunctionTest.scala
lms-jobs/relation-cache-updater/src/main/scala/org/sunbird/job/relationcache/functions/RelationCacheUpdater.scala

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.3.0

---

.circleci/config.yml
jobs-core/pom.xml
kubernetes/pipelines/build/Jenkinsfile
kubernetes/pipelines/build/auto_build_deploy
lms-jobs/credential-generator/certificate-processor/pom.xml

LR-627 | Cloud agnostic changes added

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

LR-627 | j2 template changes for Cloud agnostic

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #LR-627 | variable changes for cloud agnostic

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2

LR-627 | Helm changes for cloud agnostic

---

ansible/roles/setup-lern-kafka/defaults/main.yml
jobs-distribution/pom.xml
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2
user-org-jobs/user-deletion-cleanup/src/main/resources/user-deletion-cleanup.conf
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/task/UserDeletionCleanupConfig.scala
user-org-jobs/user-deletion-cleanup/src/test/resources/test.conf

Issue #LR-676 feat: Delete User cleanup

---

ml-jobs/ml-user-delete/pom.xml
ml-jobs/program-user-info/pom.xml

Issue #LR-708: Fixed vulnerability issues for ml modules

---

kubernetes/helm_charts/datapipeline_jobs/values.j2
lms-jobs/credential-generator/collection-certificate-generator/src/main/resources/collection-certificate-generator.conf
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/task/CertificateGeneratorConfig.scala
lms-jobs/credential-generator/collection-certificate-generator/src/test/resources/test.conf
lms-jobs/credential-generator/collection-certificate-generator/src/test/scala/org/sunbird/job/certgen/spec/CertificateGeneratorFunctionTest.scala

Authentication token added for RC certificate creation

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

Issue #LR-676 chore: Updated the classpath

---

user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/functions/UserCacheUpdaterFunctionV2.scala

Issue #LR-750 fix:user-deletion-status-fix

---

user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/functions/UserCacheUpdaterFunctionV2.scala

User deletion status fix

---

user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/task/UserCacheUpdaterConfigV2.scala
user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/util/UserMetadataUpdater.scala

Issue #LR-756 feat:adding status column

---

ansible/roles/setup-lern-kafka/defaults/main.yml
jobs-core/pom.xml
jobs-core/src/main/resources/base-config.conf
jobs-core/src/main/scala/org/sunbird/job/BaseJobConfig.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/CertificateFactory.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/CertificateGenerator.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/pojos/valuator/IssuedDateValuator.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/processor/views/SvgGenerator.scala
lms-jobs/credential-generator/certificate-processor/src/main/scala/org/sunbird/incredible/processor/views/VarResolver.scala
lms-jobs/credential-generator/collection-certificate-generator/src/main/scala/org/sunbird/job/certgen/functions/CertificateGeneratorFunction.scala
lms-jobs/credential-generator/legacy-certificate-migrator/src/main/scala/org/sunbird/job/certmigrator/functions/CertificateGeneratorFunction.scala
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/domain/Event.scala
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/functions/UserDeletionCleanupFunction.scala
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/task/UserDeletionCleanupConfig.scala
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/task/UserDeletionCleanupStreamTask.scala
user-org-jobs/user-deletion-cleanup/src/test/scala/org/sunbird/deletioncleanup/spec/UserDeletionCleanupFunctionTestSpec.scala
user-org-jobs/user-ownership-transfer/src/main/resources/user-ownership-transfer.conf
user-org-jobs/user-ownership-transfer/src/main/scala/org/sunbird/job/ownershiptransfer/functions/UserOwnershipTransferFunction.scala
user-org-jobs/user-ownership-transfer/src/main/scala/org/sunbird/job/ownershiptransfer/task/UserOwnershipTransferConfig.scala
user-org-jobs/user-ownership-transfer/src/main/scala/org/sunbird/job/ownershiptransfer/task/UserOwnershipTransferStreamTask.scala
user-org-jobs/user-ownership-transfer/src/test/scala/org/sunbird/ownershiptransfer/spec/UserOwnershipTransferFunctionTestSpec.scala

Issue #LR-685 feat: Ownership Transfer

---

user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/job/usercache/functions/UserCacheUpdaterFunctionV2.scala
user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/job/usercache/task/UserCacheUpdaterConfigV2.scala
user-org-jobs/user-cache-updater-2.0/src/main/scala/org/sunbird/job/usercache/util/UserMetadataUpdater.scala

Merge from Release 7.0.0 to Release 8.0.0

---

user-org-jobs/user-deletion-cleanup/pom.xml
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/util/KeyCloakConnectionProvider.scala

Issue #LR-327 chore: keycloak-21 changes wrto datapipeline

---

kubernetes/helm_charts/datapipeline_jobs/values.j2
user-org-jobs/user-deletion-cleanup/src/main/resources/user-deletion-cleanup.conf
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/domain/Event.scala
user-org-jobs/user-deletion-cleanup/src/main/scala/org/sunbird/job/deletioncleanup/functions/UserDeletionCleanupFunction.scala

Issue #LR-684 fix: user-deletion-fix refactored user deletion cleanup

---

jobs-distribution/Dockerfile

The base image has gcp supportive jar

Issue #LR-000 fix: Updated flink base image

---

jobs-distribution/Dockerfile

Improve the Dockerfile by upgrading the base image and installing `imagemagick` with optimizations to address image vulnerabilities.
The updates are made to fix known vulnerabilities in the Docker image and enhance security by using the `--no-install-recommends` option to minimize unnecessary packages, and cleaning up after …

SBCOSS-412: Updated the docker file-fixing image vulnerabilities

---

jobs-core/pom.xml
lms-jobs/credential-generator/certificate-processor/pom.xml

This PR applies security vulnerability fixes by updating dependencies to patched versions and aligning libraries across modules to ensure compliance, stability, and compatibility.
Update and manage dependencies in the Maven `pom.xml` files across `jobs-core` and `lms-jobs/credential-generator/certificate-processor` by implementing exclusions for vulnerable artifacts and adding specific versions of reintroduced dependencies to address security vulnerabilities.
These changes are being made to mitigate security vulnerabilities by excluding potentially harmful dependencies, replacing them with secure, updated versions where necessary, and maintaining compatibility with project requirements. This approach ensures both security and functionality by carefully managing dependency versions and …

Issue #SBCOSS-595 fix: Vulnerability fixes
